"""MCP Tool Registry — registers and dispatches Claude-callable SAP security tools."""

from __future__ import annotations

import logging
import time
import uuid
from typing import Any

import redis as redis_lib

from integrishield.m05.config import settings
from integrishield.m05.models import McpQueryEvent, McpToolDefinition, McpToolResult
from integrishield.m05.services.event_cache import EventCache

logger = logging.getLogger(__name__)

# Tool definitions exposed to LLMs
_TOOL_DEFINITIONS: list[McpToolDefinition] = [
    McpToolDefinition(
        name="query_events",
        description=(
            "Query recent SAP API call events intercepted by IntegriShield. "
            "Returns a list of RFC call records with user, IP, function module, and bytes transferred."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "default": 20, "description": "Max events to return (1–100)"},
                "since_minutes": {"type": "integer", "default": 60, "description": "Look back N minutes"},
                "tenant_id": {"type": "string", "default": "", "description": "Filter by tenant"},
            },
        },
    ),
    McpToolDefinition(
        name="get_anomaly_scores",
        description=(
            "Retrieve recent anomaly detection scores from IntegriShield's ML engine. "
            "Returns events scored by the IsolationForest model with anomaly probability."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "default": 20, "description": "Max anomaly events to return"},
                "since_minutes": {"type": "integer", "default": 60},
            },
        },
    ),
    McpToolDefinition(
        name="list_alerts",
        description=(
            "List recent security alerts generated by IntegriShield's rules engine. "
            "Includes bulk extraction, off-hours RFC, shadow endpoint, velocity anomaly, and other scenarios."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "default": 20},
                "severity": {
                    "type": "string",
                    "enum": ["critical", "high", "medium", "low", ""],
                    "default": "",
                    "description": "Filter by severity (empty = all)",
                },
                "since_minutes": {"type": "integer", "default": 60},
            },
        },
    ),
    McpToolDefinition(
        name="run_security_check",
        description=(
            "Evaluate a single SAP RFC call event against IntegriShield's detection rules. "
            "Provide an event dict and receive an alert result (or null if clean)."
        ),
        input_schema={
            "type": "object",
            "required": ["event"],
            "properties": {
                "event": {
                    "type": "object",
                    "description": (
                        "SAP RFC call event dict with fields: event_id, source_ip, user_id, "
                        "function_module, bytes_transferred, off_hours (bool), unknown_endpoint (bool)"
                    ),
                }
            },
        },
    ),
]


class McpToolRegistry:
    """Dispatches MCP tool calls and publishes audit events to Redis."""

    def __init__(self, cache: EventCache, redis_client: redis_lib.Redis | None = None) -> None:
        self._cache = cache
        self._redis = redis_client

    def list_tools(self) -> list[McpToolDefinition]:
        return list(_TOOL_DEFINITIONS)

    def call(self, tool_name: str, arguments: dict[str, Any], session_id: str = "", tenant_id: str = "") -> McpToolResult:
        start = time.monotonic()
        try:
            result_data = self._dispatch(tool_name, arguments, tenant_id)
            latency_ms = int((time.monotonic() - start) * 1000)
            result = McpToolResult(
                tool_name=tool_name,
                result=result_data,
                latency_ms=latency_ms,
            )
            self._publish_event(tool_name, session_id, tenant_id, latency_ms, is_error=False)
            return result
        except Exception as exc:
            latency_ms = int((time.monotonic() - start) * 1000)
            self._publish_event(tool_name, session_id, tenant_id, latency_ms, is_error=True)
            return McpToolResult(
                tool_name=tool_name,
                is_error=True,
                error_message=str(exc),
                latency_ms=latency_ms,
            )

    def _dispatch(self, tool_name: str, arguments: dict[str, Any], tenant_id: str) -> Any:
        if tool_name == "query_events":
            return self._query_events(arguments, tenant_id)
        elif tool_name == "get_anomaly_scores":
            return self._get_anomaly_scores(arguments)
        elif tool_name == "list_alerts":
            return self._list_alerts(arguments)
        elif tool_name == "run_security_check":
            return self._run_security_check(arguments)
        else:
            raise ValueError(f"Unknown tool: {tool_name!r}. Available: {[t.name for t in _TOOL_DEFINITIONS]}")

    def _query_events(self, args: dict, tenant_id: str) -> dict:
        limit = min(int(args.get("limit", 20)), 100)
        since_minutes = int(args.get("since_minutes", 60))
        events = self._cache.get_recent("api_call_events", limit=limit, since_minutes=since_minutes)
        return {"events": events, "total": len(events)}

    def _get_anomaly_scores(self, args: dict) -> dict:
        limit = min(int(args.get("limit", 20)), 100)
        since_minutes = int(args.get("since_minutes", 60))
        events = self._cache.get_recent("anomaly_events", limit=limit, since_minutes=since_minutes)
        return {"anomaly_events": events, "total": len(events)}

    def _list_alerts(self, args: dict) -> dict:
        limit = min(int(args.get("limit", 20)), 100)
        since_minutes = int(args.get("since_minutes", 60))
        severity_filter = args.get("severity", "")
        alerts = self._cache.get_recent("alert_events", limit=limit * 3, since_minutes=since_minutes)
        if severity_filter:
            alerts = [a for a in alerts if a.get("severity") == severity_filter]
        return {"alerts": alerts[:limit], "total": len(alerts)}

    def _run_security_check(self, args: dict) -> dict:
        """Inline rules evaluation — same logic as m12 service but self-contained."""
        event = args.get("event", {})
        if not event:
            raise ValueError("'event' argument is required and must be a non-empty dict")

        # Import evaluate_event logic inline to avoid cross-module dep
        alerts = []
        bytes_out = int(event.get("bytes_transferred", event.get("bytes_out", 0)))
        if bytes_out > 10_000_000:
            alerts.append({"scenario": "bulk-extraction", "severity": "critical", "detail": f"{bytes_out / 1e6:.1f}MB transferred"})
        if event.get("off_hours"):
            alerts.append({"scenario": "off-hours-rfc", "severity": "medium", "detail": "Off-hours API call"})
        if event.get("unknown_endpoint"):
            alerts.append({"scenario": "shadow-endpoint", "severity": "critical", "detail": "Unknown RFC endpoint"})

        return {"alert": alerts[0] if alerts else None, "matched": bool(alerts), "all_alerts": alerts}

    def _publish_event(self, tool_name: str, session_id: str, tenant_id: str, latency_ms: int, is_error: bool) -> None:
        if self._redis is None:
            return
        try:
            event = McpQueryEvent(
                event_id=str(uuid.uuid4()),
                session_id=session_id,
                tool_name=tool_name,
                tenant_id=tenant_id,
                latency_ms=latency_ms,
                is_error=is_error,
            )
            self._redis.xadd(settings.publish_stream, {"data": event.model_dump_json()})
        except Exception:
            logger.exception("Failed to publish MCP query event")
